// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresupuestoFamiliarApp.Data;

#nullable disable

namespace PresupuestoFamiliarApp.Migrations
{
    [DbContext(typeof(PresupuestoContext))]
    [Migration("20260220111826_AgregarTarjetaCredito")]
    partial class AgregarTarjetaCredito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PresupuestoMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasGastos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Comida",
                            PresupuestoMensual = 500m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vivienda",
                            PresupuestoMensual = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Transporte",
                            PresupuestoMensual = 150m
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Gastos personales",
                            PresupuestoMensual = 200m,
                            Subcategoria = "Peluquería, móvil, deporte"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Gastos de mascota",
                            PresupuestoMensual = 100m
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Servicios de casa",
                            PresupuestoMensual = 200m,
                            Subcategoria = "Luz, agua, gas, internet"
                        });
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCredito")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCredito = false,
                            Nombre = "Cuenta Roberto",
                            SaldoActual = 0m
                        },
                        new
                        {
                            Id = 2,
                            EsCredito = false,
                            Nombre = "Cuenta Ivette",
                            SaldoActual = 0m
                        },
                        new
                        {
                            Id = 3,
                            EsCredito = false,
                            Nombre = "Efectivo",
                            SaldoActual = 0m
                        });
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsTransferencia")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Transaccion", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.CategoriaGasto", "Categoria")
                        .WithMany("Transacciones")
                        .HasForeignKey("CategoriaGastoId");

                    b.HasOne("PresupuestoFamiliarApp.Models.Cuenta", "Cuenta")
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CategoriaGasto", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Cuenta", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
