// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresupuestoFamiliarApp.Data;

#nullable disable

namespace PresupuestoFamiliarApp.Migrations
{
    [DbContext(typeof(PresupuestoContext))]
    partial class PresupuestoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspacioUsuario", b =>
                {
                    b.Property<int>("EspaciosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.HasKey("EspaciosId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("EspacioUsuario");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("MonedaCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PresupuestoMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.ToTable("CategoriasGastos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EspacioId = 1,
                            MonedaCategoria = 0,
                            Nombre = "Comida",
                            PresupuestoMensual = 500m
                        },
                        new
                        {
                            Id = 2,
                            EspacioId = 1,
                            MonedaCategoria = 0,
                            Nombre = "Vivienda",
                            PresupuestoMensual = 1000m
                        },
                        new
                        {
                            Id = 3,
                            EspacioId = 1,
                            MonedaCategoria = 0,
                            Nombre = "Transporte",
                            PresupuestoMensual = 150m
                        },
                        new
                        {
                            Id = 4,
                            EspacioId = 1,
                            MonedaCategoria = 0,
                            Nombre = "Gastos personales",
                            PresupuestoMensual = 200m,
                            Subcategoria = "Peluquería, móvil, deporte"
                        },
                        new
                        {
                            Id = 5,
                            EspacioId = 1,
                            MonedaCategoria = 0,
                            Nombre = "Gastos de mascota",
                            PresupuestoMensual = 100m
                        },
                        new
                        {
                            Id = 6,
                            EspacioId = 1,
                            MonedaCategoria = 0,
                            Nombre = "Servicios de casa",
                            PresupuestoMensual = 200m,
                            Subcategoria = "Luz, agua, gas, internet"
                        });
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsCredito")
                        .HasColumnType("bit");

                    b.Property<int>("EspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("MonedaCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.ToTable("Cuentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsCredito = false,
                            EspacioId = 1,
                            MonedaCuenta = 0,
                            Nombre = "Cuenta Roberto",
                            SaldoActual = 0m
                        },
                        new
                        {
                            Id = 2,
                            EsCredito = false,
                            EspacioId = 1,
                            MonedaCuenta = 0,
                            Nombre = "Cuenta Ivette",
                            SaldoActual = 0m
                        },
                        new
                        {
                            Id = 3,
                            EsCredito = false,
                            EspacioId = 1,
                            MonedaCuenta = 0,
                            Nombre = "Efectivo",
                            SaldoActual = 0m
                        });
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CuentaPorCobrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeudorId")
                        .HasColumnType("int");

                    b.Property<bool>("EsAlquiler")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaDeuda")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeudorId");

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Deudor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspacioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.ToTable("Deudores");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Espacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonedaPrincipal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Espacios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonedaPrincipal = 0,
                            Nombre = "Mi Casa"
                        });
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.MovimientoFijo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaDelMes")
                        .HasColumnType("int");

                    b.Property<int>("EspacioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrecuenciaRepeticion")
                        .HasColumnType("int");

                    b.Property<int>("MonedaMovimiento")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaGeneracion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("CuentaId");

                    b.ToTable("MovimientosFijos");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.TipoCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaDestino")
                        .HasColumnType("int");

                    b.Property<int>("MonedaOrigen")
                        .HasColumnType("int");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("TiposCambio");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaGastoId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsTransferencia")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaTransaccion")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TasaCambioUsada")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaGastoId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonedaPreferida")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TourCompletado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rtres.info@gmail.com",
                            MonedaPreferida = 0,
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$lGmNXDsL0GHkEtaFW1YEBuOb3V8o2rdyK2jB8Wi3FuW6iZSB2g8Em",
                            Rol = "Administrador",
                            TourCompletado = false
                        });
                });

            modelBuilder.Entity("EspacioUsuario", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspaciosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresupuestoFamiliarApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CategoriaGasto", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.Espacio", "Espacio")
                        .WithMany("Categorias")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Cuenta", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.Espacio", "Espacio")
                        .WithMany("Cuentas")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CuentaPorCobrar", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.Deudor", "Deudor")
                        .WithMany("CuentasPorCobrar")
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Deudor", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.Espacio", "Espacio")
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.MovimientoFijo", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.CategoriaGasto", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaGastoId");

                    b.HasOne("PresupuestoFamiliarApp.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Transaccion", b =>
                {
                    b.HasOne("PresupuestoFamiliarApp.Models.CategoriaGasto", "Categoria")
                        .WithMany("Transacciones")
                        .HasForeignKey("CategoriaGastoId");

                    b.HasOne("PresupuestoFamiliarApp.Models.Cuenta", "Cuenta")
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.CategoriaGasto", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Cuenta", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Deudor", b =>
                {
                    b.Navigation("CuentasPorCobrar");
                });

            modelBuilder.Entity("PresupuestoFamiliarApp.Models.Espacio", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
